# Generated by Django 4.2.7 on 2025-10-12 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('breed', models.CharField(max_length=100)),
                ('supplier', models.CharField(max_length=100)),
                ('badge_id', models.CharField(max_length=50, unique=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('birth_date', models.DateField()),
                ('date_acquired', models.DateField()),
                ('current_status', models.CharField(choices=[('In Training', 'In Training'), ('In Service', 'In Service'), ('Retired', 'Retired'), ('Left', 'Left')], max_length=20)),
                ('leaving_date', models.DateField(blank=True, null=True)),
                ('leaving_reason', models.CharField(blank=True, choices=[('Transferred', 'Transferred'), ('Retired (Put Down)', 'Retired (Put Down)'), ('KIA', 'KIA'), ('Rejected', 'Rejected'), ('Retired (Re-housed)', 'Retired (Re-housed)'), ('Died', 'Died')], max_length=50, null=True)),
                ('kennelling_characteristic', models.TextField(blank=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
